Writable:
  InsecureSecrets:
    DB:
      SecretName: "redisdb"
      SecretData:
        username: ''
        password: ''
    HTTPS:
      SecretName: "https"
      SecretData:
        cert: ''
        key: ''
Clients:
  core-metadata:
    Protocol: http
    Host: localhost
    Port: 59881
  core-command:
    Protocol: http
    Host: localhost
    Port: 59882
  support-notifications:
    Protocol: http
    Host: localhost
    Port: 59860
Registry:
  Host: localhost
  Port: 8500
  Type: consul
Database:
  Type: redisdb
  Host: localhost
  Port: 6379
  Timeout: 30s
MessageBus:
  Protocol: "redis"
  Host: "edgex-redis"
  Port: 6379
  Type: "redis"
  AuthMode: "usernamepassword"  # required for redis MessageBus (secure or insecure).
  SecretName: "redisdb"
  BaseTopicPrefix: "edgex" # prepended to all topics as "edgex/<additional topic levels>
  Optional:
    # Default MQTT Specific options that need to be here to enable environment variable overrides of them
    Qos: "0" # Quality of Service values are 0 (At most once), 1 (At least once) or 2 (Exactly once)
    KeepAlive: "10" # Seconds (must be 2 or greater)
    Retained: "false"
    AutoReconnect: "true"
    ConnectTimeout: "5" # Seconds
    SkipCertVerify: "false"
    # Additional Default NATS Specific options that need to be here to enable environment variable overrides of them
    Format: "nats"
    RetryOnFailedConnect: "true"
    QueueGroup: ""
    Durable: ""
    AutoProvision: "false"
    Deliver: "new"
    DefaultPubRetryAttempts: "2"
    Subject: "edgex/#" # Required for NATS JetStream only for stream auto-provisioning