Writable:
  LogLevel: "INFO"
  Telemetry:
    Interval: "0s"

Service:
  Port: 59740
  StartupMsg: "app-surveillance started"

MessageBus:
  Disabled: false
  Optional:
    ClientId: app-surveillance
    AutoProvision: "true" #only for one service
Trigger:
  Type: edgex-messagebus
  SubscribeTopics: edgex/events/#
  PublishTopic: alarms/acknowledged
ApplicationSettings:
  DeviceNames: >-
    Random-Boolean-Device, Random-Integer-Device, Random-UnsignedInteger-Device,
    Random-Float-Device, Random-Binary-Device
Surveillance:
  CameraName: ipcam
  SnapshotCommandName: Snapshot